- name: Deploy wiseSQL
  import_tasks: sql.yml
  tags:
    - sql

- name: Backup wiseSQL
  import_tasks: sql-backup.yml
  tags:
    - sql
    - sql-backup
    - backup

- name: Setup wiseSQL monitoring
  import_tasks: monitoring.yml
  tags:
    - sql
    - sql-monitoring
    - monitoring
