---
- name: Clone steem-wise-test repository
  become: yes
  git:
    #ยง 'repo="https://github.com/' + data.config.repository.github.organization + '/steem-wise-test.git"'
    repo="https://github.com/wise-team/steem-wise-test.git"
    dest="/opt/wise/test"
    accept_hostkey=yes
    version={{ checkout_branch }}
    force=yes

- name: Notify on slack
  shell: |
    WEBHOOK_URL="{{ slack_webhook_url }}"
    curl -X POST -H 'Content-type: application/json' --fail --silent --show-error --data '{"text":"Deploying steem-wise-test/healthcheck via ansible playbook"}' "${WEBHOOK_URL}" > /dev/null
  register: webhook_result
  failed_when: ( webhook_result.rc not in [ 0 ] )

- name: Save webhook url
  become: yes
  copy:
    content: "{{ slack_webhook_url }}"
    #ยง 'dest: "' + data.config.test.healthcheck.slack.webhookUrlFilePath + '"'
    dest: "/opt/wise/slackWebhook.url"
  no_log: true

- name: "Setup wise healthcheck cron job"
  cron:
    name: "Steem-wise-test healthcheck"
    minute: "0"
    hour: "*"
    job: "/opt/wise/test/healthcheck/healthcheck-run-{{ wise_environment_type }}.sh > {{ cron_log_path }} 2>&1"

- name: "Run the healthcheck immediately"
  command: "/opt/wise/test/healthcheck/healthcheck-run-{{ wise_environment_type }}.sh"
  register: immediate_healthcheck_result

- debug: msg={{ immediate_healthcheck_result.stdout.split('\n') }}

- debug: msg={{ immediate_healthcheck_result.stderr.split('\n') }}

- name: Start hosted logs service
  docker_service:
    project_src: /opt/wise/test/healthcheck/host-logs
    files:
      - docker-compose.yml
    nocache: yes
    recreate: always
    restarted: yes
