---
- hosts: all

  vars_prompt:
    - name: "deploying_user"
      prompt: "user"
      private: no
      
    - name: ansible_become_pass
      prompt: "sudo password"
      private: yes

  remote_user: "{{deploying_user}}"

  roles:
    - common
    - proxy
    - sql
    #- hub
    #- voting-page
    #- manual
    #- healthcheck
    - voting-page
    - manual
