---
- hosts: all

  vars_prompt:
    - name: "deploying_user"
      prompt: "user"
      private: no

    - name: ansible_become_pass
      prompt: "sudo password"
      private: yes

    - name: "vault_approle_provisioner_username"
      prompt: "Vault AppRole provisioner username"
      private: no

    - name: "vault_approle_provisioner_password"
      prompt: "Vault AppRole provisioner password"
      private: yes

  remote_user: "{{deploying_user}}"

  roles:
    - common
    - proxy
    - sql
    - hub
    - voting-page
    - manual
