all:
  hosts:
    #ยง data.config.environments.staging.host + ':'
    tmp.wise.vote:
      wise_environment_type: production
      #ยง 'checkout_branch: ' + data.config.environments.staging.deployBranch
      checkout_branch: master
