all:
  hosts:
    #ยง data.config.environments.production.host + ':'
    wise.vote:
      wise_environment_type: production
      #ยง 'checkout_branch: ' + data.config.environments.production.deployBranch
      checkout_branch: master
