all:
  hosts:
    #ยง data.config.environments.staging.host + ':'
    staging.wise.vote:
      wise_environment_type: staging
      #ยง 'checkout_branch: ' + data.config.environments.staging.deployBranch
      checkout_branch: staging
