---
- hosts: all
  vars_prompt:
    - name: "deploying_user"
      prompt: "user"
      private: no
      
    - name: ansible_become_pass
      prompt: "sudo password"
      private: yes

  remote_user: "{{deploying_user}}"

  tasks:
    - name: Create network 'caddy-proxy'
      docker_network:
        name: caddy-proxy
      tags:
        - caddy

    - name: Deploying caddy
      include: caddy.yml
      tags:
        - caddy

    - name: Deploying Manual
      include: manual.yml
      tags:
        - manual

    - name: Deploying wiseSQL
      include: sql.yml
      tags:
        - sql

    - name: Deploying Voting Page
      include: voting-page.yml
      tags:
        - voting-page
