---
- name: Clone Wise Voting Page repository
  become: yes
  git:
    #ยง 'repo="https://github.com/' + data.config.repository.github.organization + '/steem-wise-voter-page.git"'
    repo="https://github.com/wise-team/steem-wise-voter-page.git"
    dest="/opt/wise/voting-page"
    accept_hostkey=yes
    version={{ checkout_branch }}
    force=yes

- name: Build voting-page container
  docker_service:
    project_src: /opt/wise/voting-page
    files: 
      - docker-compose.yml
    build: yes
    nocache: yes
    recreate: always
    restarted: yes