---
- name: Clone Wise Manual repository
  become: yes
  git:
    #ยง 'repo="https://github.com/' + data.config.repository.github.organization + '/steem-wise-manual.git"'
    repo="https://github.com/wise-team/steem-wise-manual.git"
    dest="/opt/wise/manual"
    accept_hostkey=yes
    version={{ checkout_branch }}
    force=yes

- name: Build wiseManual container
  docker_service:
    project_src: /opt/wise/manual
    files: 
      - docker-compose.yml
    build: yes
    nocache: yes
    recreate: always
    restarted: yes
