---
- name: Clone Wise Manual repository
  become: yes
  git:
    #ยง 'repo="https://github.com/' + data.config.repository.github.organization + '/steem-wise-manual.git"'
    repo="https://github.com/wise-team/steem-wise-manual.git"
    dest="/opt/wise/manual"
    accept_hostkey=yes
    version={{ checkout_branch }}
    force=yes

- name: Copy static site to nginx html dir
  shell: |
    mkdir -p /opt/wise/proxy/html/manual/
    cp -R /opt/wise/manual/_site/* /opt/wise/proxy/html/manual/
  become: yes

