- name: Create {{ cron_log_path }}
  copy:
    content: ''
    dest: "{{ cron_log_path }}"
  creates: "{{ cron_log_path }}"
  become: yes
  tags:
    - common
    - cron

- name: Ensure {{ cron_log_path }} has proper permissions
  become: yes
  file: state=file path={{ cron_log_path }} mode=u+rw,g+rw,o+rw
  tags:
    - common
    - cron
