- name: Ensure local certs directory exists
  become: yes
  file: state=directory path=/usr/share/ca-certificates

- name: Install wise-vault cert .crt to ca-certificates
  become: yes
  copy: src=VaultWiseVoteCA.crt dest=/usr/share/ca-certificates/VaultWiseVoteCA.crt

- name: Install wise-vault cert .pem to ca-certificates
  become: yes
  copy: src=VaultWiseVoteCA.pem dest=/usr/share/ca-certificates/VaultWiseVoteCA.pem

- name: Install wise-vault cert .crt to ssl certs
  become: yes
  copy: src=VaultWiseVoteCA.crt dest=/etc/ssl/certs/VaultWiseVoteCA.crt

- name: Install wise-vault cert .pem to ssl certs
  become: yes
  copy: src=VaultWiseVoteCA.pem dest=/etc/ssl/certs/VaultWiseVoteCA.pem

- name: Update cert index
  become: yes
  shell: /usr/sbin/update-ca-certificates