---
- name: Setup remote logging from all docker containers in logzio
  docker_container:
    name: logzio
    image: logzio/logzio-docker
    command: "-t {{ logzio_token }} -a {{ wise_environment_type }}"
    detach: true
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    restart_policy: always
  tags:
    - remote_logs
