
- name: "Setup cron job for docker system prune"
  become: "yes"
  cron:
    name: "Docker system prune -f"
    hour: "*/12"
    job: "/usr/bin/env sh -c \"echo \\\"Running docker system prune...\\\" && docker system prune -f && echo \\\"Docker system prune done\\\" >> {{ cron_log_path }} 2>&1 \""
  tags:
    - clean
    - common

- name: Setup remote logging service
  import_tasks: log.yml
  tags:
    - log
    - common

- name: Install wise vault cert
  import_tasks: install-vault-cert.yml
  tags:
    - common
    - vault
