- name: Ensure deployment scripts directory {{ scripts_path }}
  become: yes
  file: state=directory path={{ scripts_path }}
  tags:
    - common
    - scripts

- name: Copy deployment scripts to {{ scripts_path }}
  become: yes
  copy: src=scripts dest={{ scripts_path | dirname }} mode=u+rwx,g+rwx,o+rwx
  tags:
    - common
    - scripts

- name: Setup cron
  import_tasks: cron-setup.yml
  tags:
    - cron-setup
    - common

- name: Setup cron job for docker system prune
  become: yes
  cron:
    name: "Docker system prune -f"
    hour: "*/24"
    job: >-
      CRON_JOB_NAME="Docker system prune cron job"
      {{ scripts_path }}/wrap-cron.sh docker system prune -f
  tags:
    - clean
    - common

- name: Setup remote logging service
  import_tasks: log.yml
  tags:
    - log
    - common

- name: Install wise vault cert
  import_tasks: install-vault-certs.yml
  tags:
    - common
    - vault
