- name: Build backend
  command: "{{ hub_path }}/backend/build.sh"
  register: backend_build_script_result
  failed_when: ( backend_build_script_result.rc not in [ 0 ] )
  tags:
    - hub-backend-build-stack

- name: Undeploy old stack
  command: "{{ hub_path }}/scripts/undeploy.sh"
  register: undeploy_script_result
  failed_when: ( undeploy_script_result.rc not in [ 0 ] )
  tags:
    - hub-backend-undeploy-stack

- name: Wait for undeployment
  command: sleep 15
  tags:
    - hub-backend-undeploy-stack

- name: Provision AppRole secrets for wise hub
  import_tasks: provision-approle.yml
  tags:
    - hub-backend-provision-secrets

- name: Deploy wise hub stack
  command: "{{ hub_path }}/scripts/deploy-{{ wise_environment_type }}.sh"
  register: deploy_script_result
  failed_when: ( deploy_script_result.rc not in [ 0 ] )
  tags:
    - hub-backend-deploy-stack
