---
- name: Clone wiseHUB repository
  become: yes
  git:
    #ยง 'repo="https://github.com/' + data.config.repository.github.organization + '/wise-hub.git"'
    repo="https://github.com/wise-team/wise-hub.git"
    dest="{{ hub_path }}"
    accept_hostkey=yes
    version={{ checkout_branch }}
    force=yes
  tags:
    - hub-clone
