---
- name: Clone wiseHUB repository
  become: yes
  git:
    #ยง 'repo="https://github.com/' + data.config.repository.github.organization + '/wise-hub.git"'
    repo="https://github.com/wise-team/wise-hub.git"
    dest="/opt/wise/hub"
    accept_hostkey=yes
    version={{ checkout_branch }}
    force=yes
  tags:
    - hub_backend
    - hub_frontend

- name: Build backend
  command: /opt/wise/hub/backend/build.sh
  register: backend_build_script_result
  failed_when: ( backend_build_script_result.rc not in [ 0 ] )
  tags:
    - hub_backend

- name: Build frontend
  command: /opt/wise/hub/wise-hub-frontend/scripts/build-with-docker.sh
  register: frontend_build_script_result
  failed_when: ( frontend_build_script_result.rc not in [ 0 ] )
  tags:
    - hub_frontend

- name: Deploy wise hub stack
  command: /opt/wise/hub/scripts/deploy-{{ wise_environment_type }}.sh
  register: deploy_script_result
  failed_when: ( deploy_script_result.rc not in [ 0 ] )
  tags:
    - hub_backend
    - hub_frontend

#- name: Ask for vault username
#  pause:
#    prompt: "Enter vault username"
#  register: vault_username
#
#- name: Ask for vault password
#  pause:
#    prompt: "Enter vault password"
#    echo: no
#  register: vault_password

#- name: "Provision secrets"
#  become: yes
#  shell: |
#    USERPASS_USERNAME="{{ vault_username.user_input }}"
#    USERPASS_PASS="{{ vault_password.user_input }}"
#    bash /opt/wise/hub/install-secrets.sh
#  register: provision_result
#  failed_when: provision_result.rc != 0

#- name: Secrets not present
#  stat: path=/run/wise/secrets/hub-api-approle-secret
#  register: sec_exists

#- name: fail if already run on host
#  fail: msg="Secrets not provisioned"
#  when: sec_exists.sec_exists.exists == False

#- name: Build wiseHUB docker container
#  docker_service:
#    project_src: /opt/wise/hub
#    files:
#      - docker-compose.yml
#      - "docker-compose.{{ wise_environment_type }}.yml"
#    build: yes
#    nocache: yes
#    recreate: always
#    restarted: yes
    
