- import_tasks: maintenance_on.yml
  tags:
    - hub
    - hub-clone
    - hub-monitoring
    - hub-frontend
    - hub-backend

- name: Clone wise hub
  import_tasks: clone.yml
  tags:
    - hub
    - hub-clone
    - hub-monitoring
    - hub-frontend
    - hub-backend

- name: Build and deploy frontend
  import_tasks: frontend.yml
  tags:
    - hub
    - hub-frontend

- name: Build and deploy hub backend
  import_tasks: backend.yml
  tags:
    - hub
    - hub-backend

- name: Backup wise hub
  import_tasks: backup.yml
  tags:
    - hub
    - hub-backup
    - backup

- name: Setup hub monitoring
  import_tasks: monitoring.yml
  tags:
    - hub
    - hub-monitoring

- import_tasks: maintenance_off.yml
  tags:
    - hub
    - hub-clone
    - hub-monitoring
    - hub-frontend
    - hub-backend
